test:
  deploymentName: hello-deployment
  image: southamerica-west1-docker.pkg.dev/project-f37a4860-d512-457a-b73/docker-repo/hello:1.0.10
  replicas: 2
  serviceName: hello-service
  servicetype: NodePort
